# https://dev.azure.com/home-assistant

trigger:
  branches:
    include:
    - master
pr:
- master

variables:
  versionHadolint: 'v1.16.3'
  versionShellCheck: 'v0.6.0'
  versionBuilder: '1.3'

jobs:

- job: 'Hadolint'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker pull hadolint/hadolint:$(versionHadolint)
    displayName: 'Install Hadolint'
  - script: |
      set -e
      shopt -s globstar
      for dockerfile in **/Dockerfile
      do
        echo "Linting: $dockerfile"
        sudo docker run --rm -i \
          -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
          hadolint/hadolint:$(versionHadolint) < "$dockerfile"
      done
    displayName: 'Run Hadolint'


- job: 'ShellCheck'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker pull koalaman/shellcheck:$(versionShellCheck)
    displayName: 'Install ShellCheck'
  - script: |
      shopt -s globstar
      sudo docker run --rm -i \
        -v $(pwd):/mnt:ro koalaman/shellcheck:$(versionShellCheck) **/*.sh
    displayName: 'Run ShellCheck'

- job: 'JQ'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo apt-get install -y jq
    displayName: 'Install JQ'
  - bash: |
      shopt -s globstar
      cat **/*.json | jq '.'
    displayName: 'Run JQ'


- job: 'cec_scan'
  condition: and(eq(variables['Build.SourceBranchName'], 'master'), succeeded('Hadolint'), succeeded('ShellCheck'), succeeded('JQ'))
  dependsOn:
  - 'Hadolint'
  - 'ShellCheck'
  - 'JQ'
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - template: azp-template-addon.yml
    parameters:
      addon: 'cec_scan'
      arch: '--all'


- job: 'check_config'
  condition: and(eq(variables['Build.SourceBranchName'], 'master'), succeeded('Hadolint'), succeeded('ShellCheck'), succeeded('JQ'))
  dependsOn:
  - 'Hadolint'
  - 'ShellCheck'
  - 'JQ'
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - template: azp-template-addon.yml
    parameters:
      addon: 'check_config'
      arch: '--all'


- job: 'configurator'
  condition: and(eq(variables['Build.SourceBranchName'], 'master'), succeeded('Hadolint'), succeeded('ShellCheck'), succeeded('JQ'))
  dependsOn:
  - 'Hadolint'
  - 'ShellCheck'
  - 'JQ'
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - template: azp-template-addon.yml
    parameters:
      addon: 'configurator'
      arch: '--all'


- job: 'deconz'
  condition: and(eq(variables['Build.SourceBranchName'], 'master'), succeeded('Hadolint'), succeeded('ShellCheck'), succeeded('JQ'))
  dependsOn:
  - 'Hadolint'
  - 'ShellCheck'
  - 'JQ'
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - template: azp-template-addon.yml
    parameters:
      addon: 'deconz'
      arch: '--armhf --amd64'
